### ISSUE TITLE
VFS implementation for vSphere provider

### ISSUE THREAD

**Issue by luomiao** [vmware/kops#12]
Currently we are using AWS S3 for storing cluster configurations.
Need to implement a solution for vSphere provider and remove temporary hacks like:
https://github.com/vmware/kops/pull/11/files#diff-c3728f8965d9f6a965d9702a2d133ee5R113
https://github.com/vmware/kops/pull/11/files#diff-d510984f3211ef071e61626401f1f793R64

**Comment by luomiao** [comment]
Use CoreDNS VM for storage?

**Comment by luomiao** [comment]
Even to use Minio, the implementation is not trivial.
We need to implement a miniofs.go under kops/util/pkg/vfs to realize the VFS APIs.
will need more time on this issue.

**Comment by prashima** [comment]
https://github.com/vmware/kops/commit/0ed5326b2ce6c9a9d34917a4930b033feff5586f fixes this issue.
