### ISSUE TITLE
protokube/vsphere_volume should get actual device details

### ISSUE THREAD

**Issue by luomiao** [vmware/kops#15]
Now information like EtcdNodeName/EtcdClusterName and local device name are hard-coded:
https://github.com/vmware/kops/blob/vsphere-develop/protokube/pkg/protokube/vsphere_volume.go#L30

Need to get these information from actual setting.

**Comment by prashima** [comment]
https://github.com/vmware/kops/commit/723bc7f04e8503ad979ef1de408f7e4819cfb615 fixes this issue.
