### ISSUE TITLE
Cloudinit not able to complete successfully

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kops#21]
I tested this multiple times.
<img width="973" alt="screen shot 2017-03-29 at 12 06 42 pm" src="https://cloud.githubusercontent.com/assets/1269660/24471881/69876f02-1478-11e7-822b-1cda848e3570.png">

**Comment by luomiao** [comment]
hmmm I didn't see this.
Does it happen every time for you?

**Comment by SandeepPissay** [comment]
Abrar, can you upload the .var/log/cloud-init*.log files?

**Comment by abrarshivani** [comment]
I checked the logs and discovered that this was due to nodeup's sha1sum was not matching. After updating sha1sum it was working fine.
