### ISSUE TITLE
Run KOPS CI on vmware/kops nightly to prevent regressions

### ISSUE THREAD

**Issue by tusharnt** [vmware/kops#27]
Use webhooks to run KOPS CI for each PR for vmware/kops

**Comment by abrarshivani** [comment]
Added travis-ci. This makes sure ```make-ci``` pass

**Comment by abrarshivani** [comment]
There are two ci jobs that kubernetes/kops runs. First, travis-ci which make sure ```make-ci``` passes. Second, which deploys Kubernetes cluster on AWS and runs Kubernetes e2e tests.  

First ci job is added here. For second, we will have similar for vSphere.
