### ISSUE TITLE
Add vm uuid in Kubernetes vSphere Cloud Provider cloud config file 

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kops#32]
Currently, we don't add VM uuid in cloud config file. Usually, K8s cloud provider picks vm uuid which is reported by dmidecode. Yet, dmidecode reports incorrect vm uuid in Ubuntu 16.04. Hence, deployment fails in case of Kubernetes v1.5.3 and greater.

**Comment by prashima** [comment]
Discussed with Abrar, this issue is fixed now.
