### ISSUE TITLE
1st Upstream guideline

### ISSUE THREAD

**Issue by luomiao** [vmware/kops#40]
We will need to separate the upstreaming into multiple PRs for easy review process:
1. PRs for vendor codes (govmomi, coredns related vendor code)
2. PRs for kops enhancement (e.g: taking user-defined dns-controller/protokube images)
3. PRs for vsphere support

The first two PRs are going directly to kubernetes/kops.
The third PRs are going to be reviewed inside vmware/kops first.

**Comment by pdhamdhere** [comment]
@luomiao PR is merged so can we close this now?

**Comment by luomiao** [comment]
Done by https://github.com/kubernetes/kops/pull/2401
