### ISSUE TITLE
Add brief description for vSphere files/functions

### ISSUE THREAD

**Issue by luomiao** [vmware/kops#52]
Add file header comments with purpose of code in that file.
Add function header comments for exported functions (that will be called from outside)

protokube/pkg/protokube/vsphere_volume.go
upup/pkg/fi/cloudup/vsphere/vsphere_apitarget.go
upup/pkg/fi/cloudup/vsphere/vsphere_cloud.go
upup/pkg/fi/cloudup/vsphere/vsphere_volume_metadata.go
upup/pkg/fi/cloudup/vsphere/vsphere_utils.go
pkg/model/vspheremodel/autoscalinggroup.go
upup/pkg/fi/cloudup/vspheretasks/attachiso.go
upup/pkg/fi/cloudup/vspheretasks/virtualmachine.go
upup/pkg/fi/cloudup/vspheretasks/vmpoweron.go

**Comment by prashima** [comment]
https://github.com/vmware/kops/commit/59537b0985c680cbb26058603d797bccb5f2ace1 fixes this.
